const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const dogsOwnedSchema = new Schema({
    dogId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Dog'
    }
});

const dogsFavoritedSchema = new Schema({
    dogId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Dog'
    }
});

const userSchema = new Schema({
//  _id value is randomly generated by Mongo 
    name: {
        type:String,
        required:true
    },
    email: {
        type:String,
        required:true
    },
    password: {
        type:String,
        required:true
    },
    zip: {
        type:Number,
        required:false
    },
    phone: {
        type:Number,
        required:false
    },
    dogsOwned: [dogsOwnedSchema],
    dogsFavorited: [dogsFavoritedSchema],
    contactOwnerNameSwitch: {
        type:Boolean,
        required: true
    },
    contactOwnerAddressSwitch: {
        type:Boolean,
        required: true
    },
    contactOwnerPhoneSwitch: {
        type:Boolean,
        required: true
    },
    contactVetName: {
        type:String
    },
    contactVetAddress: {
        type:String
    },
    contactVetPhone: {
        type:String
    },
    contactEVetName: {
        type:String
    },
    contactEVetAddress: {
        type:String
    },
    contactEVetPhone: {
        type:String
    }
}, {
    timestamps:true
});

// User data
//     _id                   Not input - hidden
//     name:                input type text
//     email:               input type email
//     password:            input type password
//     ZIP:                 input type text
//     phone:               input type text
//     dogsOwned: [          Not input - hidden
//          {
//              "_id":"fjfjfjjf"
//          }
//      ]
//     dogsFavorited: [          Not input - hidden
//          {
//              "_id":"fjfjfjjf"
//          }
//      ]
//      "contactOwnerNameSwitch":"",                   input type boolean
//      "contactOwnerAddressSwitch":"",                input type boolean
//      "contactOwnerPhoneSwitch": ""                  input type boolean
//      "contactVetName":"PAC Animal Hospital", input type string
//      "contactVetAddress":"123 Test Street",  input type string
//      "contactVetPhone": "4101234567",        input type number
//      "contactEVetName":"Emergency Animal Hospital", input type string
//      "contactEVetAddress":"456 Test Street",  input type string
//      "contactEVetPhone": "4109876543",       input type number
//     ]

const User = mongoose.model('User', userSchema);

module.exports = User;